### ISSUE TITLE
建议使用全角符号

### ISSUE THREAD

**Issue by AkinoKaede** [xi-yu-yan-kai-fa/Xi-Yuyan#2]
文化自信  features，比如使用「」代替{}

**Comment by AkinoKaede** [comment]
特殊的运算，实现 1/3+1/5 == 2/8

**Comment by xi-yu-yan-kai-fa** [comment]
欢迎提交PR啊，为加速添砖加瓦。

**Comment by AkinoKaede** [comment]
> 欢迎提交PR啊，为加速添砖加瓦。

我连代码都没看到，连这个项目要用什么技术栈都不知道

**Comment by xi-yu-yan-kai-fa** [comment]
> > 欢迎提交PR啊，为加速添砖加瓦。
> 
> 我连代码都没看到，连这个项目要用什么技术栈都不知道

對不起！我們只在群組裡討論了😢
我們會用ANTLR4（ https://github.com/antlr/antlr4/blob/master/doc/python-target.md ）作為Lexer和Parser，然後寫一個解釋器（Python），你有興趣入Telegram的Group嗎😂

**Comment by xi-yu-yan-kai-fa** [comment]
其实我的意思是可以先把这个feature的特点作为PR提交到md里hhhh

**Comment by AkinoMaple** [comment]
> 欢迎提交PR啊，为加速添砖加瓦。
> 
> 我连代码都没看到，连这个项目要用什么技术栈都不知道
> 
> 對不起！我們只在群組裡討論了😢
> 我們會用ANTLR4（ https://github.com/antlr/antlr4/blob/master/doc/python-target.md ）作為Lexer和Parser，然後寫一個解釋器（Python），你有興趣入Telegram的Group嗎😂

Python的话我有学过，但很久没用qwq  
ANTLR的话就简单了不少 也不需要懂编译原理了  
Telegram群组的话……怎么邀请呢

**Comment by DearZh** [comment]
咳咳，我想知道源码 OR 如何加入
